services:
  mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hotelmananger
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password2025
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork: